version: '3'

services:

    site:
        restart: always
        build: ./site
        ports:
            - "8000"
        volumes: ['./site:/site']
        environment:
            MONGODB_HOST: db
            MONGODB_PORT: 27017
        links:
            - db
        #command: /usr/local/bin/gunicorn --reload --log-file=/site/log  -w 2 -b :8000 app:app
        command: python -u app.py DEVELOPMENT

        #remove reload for production
        #command: /usr/local/bin/gunicorn -w 2 -b :8001 app:app

    nginx:
        restart: always
        build: ./nginx/
        ports:
            - "80:80"
        links:
            - site

    db:
        image: mongo:3.0.2
